[package]
name = "renderer"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]

[[bin]]
name = "renderer"
path = "src/main.rs"

[dependencies]
nphysics3d = "0.8"
nalgebra = "0.14"
kiss3d = "0.14.0"
shapes = { path = "../" }
